### ISSUE TITLE
Add GTSAM as an external dependency to MRPT (Tushar Kusnur)

### ISSUE THREAD

**Issue by bergercookie** [MRPT/GSoC2018-discussions#4]
## Initial Description

The problem of Simultaneous Localization and Mapping (SLAM) has been around for many years and numerous front-end and back-end methods have been developed to solve it. SLAM is the computational problem of building a consistent map of an agent’s unknown environment while simultaneously keeping track of its location at all times within the environment. Currently, MRPT has only one available graph SLAM optimizer class, namely CLevMarqGSO, which uses the Levenberg-Marquardt algorithm to solve for the nonlinear graph SLAM optimization. We intend to support the usage of other optimization modules found in the GTSAM library (which primarily uses the iSAM2 algorithm) as an optional, external dependency in MRPT.

[Original GSoC Proposal](https://summerofcode.withgoogle.com/dashboard/organization/6305642571104256/proposal/5375903027167232/)

**Progress:** All comments below reflect the interactions between the GSoC student and the mentors.

---

* Student: @ktushar14
* Main Mentor: @bergercookie
* Backup Mentor: @taihup

**Comment by ktushar14** [comment]
Hello everyone,

First of all, I would like to thank you for accepting my proposal to GSoC 2018. This project was perfectly aligned with my experience and interests. However, I am afraid that I will most likely have to withdraw from GSoC 2018 due to the following reasons:

On 4 April, 2018, I received an offer letter from CMU's Robotics Institute for their summer program, Robotics Institute Summer Scholars (RISS) 2018, which is from 1 June, 2018 to 10 August, 2018. I had applied to this program in January 2018, and at the time of submitting my proposal for GSoC, I had no information about my selection in the program. I will be participating in the program, as I think it will immensely support my future goals of research-based graduate studies.

I have been in talks with CMU for the past two days regarding this. To participate in RISS 2018, I will be in the US on a J-1 visa with CMU. GSoC 2018's requirements mention that I must be eligible to work in the country I will reside in during the program. However, the CMU J-1 requirements state that I am not allowed to work with any organization apart from CMU during this period. 

I certainly want to work on the project part-time, and would be glad if **this particular** issue remains open. I would like to continue working on this as if GSoC were still underway, with only some relaxations applied to my time constraints.

**Comment by bergercookie** [comment]
Hey @ktushar14,

>On 4 April, 2018, I received an offer letter from CMU's Robotics Institute for their summer program, Robotics Institute Summer Scholars (RISS) 2018, which is from 1 June, 2018 to 10 August, 2018. I had applied to this program in January 2018, and at the time of submitting my proposal for GSoC, I had no information about my selection in the program. I will be participating in the program, as I think it will immensely support my future goals of research-based graduate studies.

Congratulations.

>I certainly want to work on the project part-time, and would be glad if this particular issue remains open. I would like to continue working on this as if GSoC were still underway, with only some relaxations applied to my time constraints.

Fair enough, do work on the project if you want to, and  ask any question you may have either here or post it as an issue in the MRPT repo. However, I think it makes sense to close this issue, as it's not relevant to GSoC anymore.

As a sidenote though, I personally consider this an unprofessional behavior on your end. Me and the rest of the mentors have spent time reviewing your proposal and we have also allocated a slot for your project which now cannot be regained! You should have at least made it clear that you had applied for an internship position to which you give a higher priority.

Regards,
Nikos

**Comment by jolting** [comment]
@ktushar14 Please make sure you formally withdraw from GSoC via the portal if you don't plan on participating.

Congratulations! If you're not in GSoC there shouldn't be any restrictions on contributing and we're here if you want to work on some interesting projects for open source, but the main MRPT issue tracker is the right place for that.

**Comment by ktushar14** [comment]
Thank you for understanding. This is certainly not an ideal situation for me and I never expected things to turn out this way. I apologize for the inconvenience caused, and I certainly did not intend for anything like this to happen. As for prioritizing one over the other, there was no question of choosing one of the two initially, as I found out only recently that I would not be allowed to participate in both programs together (I have seen many students manage partially overlapping internships with GSoC successfully and was confident of doing so assuming there wouldn't be any restrictions, but the J-1 visa rules in my specific case do not let me; I agree that it was my responsibility to ensure that it was possible in the first place).
